In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.neighbors import KNeighborsClassifier


In [2]:
mobile_df=pd.read_csv(r"Mobile_data.csv")

In [3]:
mobile_df

battery_power  clock_speed  fc  int_memory  m_dep  mobile_wt  n_cores  \
0               842          2.2   1           7    0.6        188        2   
1              1021          0.5   0          53    0.7        136        3   
2               563          0.5   2          41    0.9        145        5   
3               615          2.5   0          10    0.8        131        6   
4              1821          1.2  13          44    0.6        141        2   
...             ...          ...  ..         ...    ...        ...      ...   
1995            794          0.5   0           2    0.8        106        6   
1996           1965          2.6   0          39    0.2        187        4   
1997           1911          0.9   1          36    0.7        108        8   
1998           1512          0.9   4          46    0.1        145        5   
1999            510          2.0   5          45    0.9        168        6   

      pc  px_height  px_width   ram  sc_h  sc_w  talk_time  price_range  
0      2         20       756  2549     9     7         19            1  
1      6        905      1988  2631    17     3          7            2  
2      6       1263      1716  2603    11     2          9            2  
3      9       1216      1786  2769    16     8         11            2  
4     14       1208      1212  1411     8     2         15            1  
...   ..        ...       ...   ...   ...   ...        ...          ...  
1995  14       1222      1890   668    13     4         19            0  
1996   3        915      1965  2032    11    10         16            2  
1997   3        868      1632  3057     9     1          5            3  
1998   5        336       670   869    18    10         19            0  
1999  16        483       754  3919    19     4          2            3  

[2000 rows x 15 columns]

In [4]:
mobile_df.shape

(2000, 15)

In [5]:
mobile_df.describe(include="all")

battery_power  clock_speed           fc   int_memory        m_dep  \
count    2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     1.522250     4.309500    32.046500     0.501750   
std       439.418206     0.816004     4.341444    18.145715     0.288416   
min       501.000000     0.500000     0.000000     2.000000     0.100000   
25%       851.750000     0.700000     1.000000    16.000000     0.200000   
50%      1226.000000     1.500000     3.000000    32.000000     0.500000   
75%      1615.250000     2.200000     7.000000    48.000000     0.800000   
max      1998.000000     3.000000    19.000000    64.000000     1.000000   

         mobile_wt      n_cores           pc    px_height     px_width  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    140.249000     4.520500     9.916500   645.108000  1251.515500   
std      35.399655     2.287837     6.064315   443.780811   432.199447   
min      80.000000     1.000000     0.000000     0.000000   500.000000   
25%     109.000000     3.000000     5.000000   282.750000   874.750000   
50%     141.000000     4.000000    10.000000   564.000000  1247.000000   
75%     170.000000     7.000000    15.000000   947.250000  1633.000000   
max     200.000000     8.000000    20.000000  1960.000000  1998.000000   

               ram         sc_h         sc_w    talk_time  price_range  
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  
mean   2124.213000    12.306500     5.767000    11.011000     1.500000  
std    1084.732044     4.213245     4.356398     5.463955     1.118314  
min     256.000000     5.000000     0.000000     2.000000     0.000000  
25%    1207.500000     9.000000     2.000000     6.000000     0.750000  
50%    2146.500000    12.000000     5.000000    11.000000     1.500000  
75%    3064.500000    16.000000     9.000000    16.000000     2.250000  
max    3998.000000    19.000000    18.000000    20.000000     3.000000

In [6]:
mobile_df.isnull().sum()

battery_power    0
clock_speed      0
fc               0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
price_range      0
dtype: int64

In [7]:
mobile_df.dtypes

battery_power      int64
clock_speed      float64
fc                 int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
price_range        int64
dtype: object

In [8]:
X=mobile_df.values[:,:-1]
Y=mobile_df.values[:,-1]
Y=Y.astype(int)

In [9]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)

X=scaler.transform(X)

In [10]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [11]:
from sklearn.naive_bayes import GaussianNB

model_NB=GaussianNB()

model_NB.fit(X_train,Y_train)
Y_pred=model_NB.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr_knn=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by KNN  method:\n",cfmlr_knn)
print()
class_ralr_knn=classification_report(Y_test,Y_pred)
print("Classfication rep by KNN method:\n",class_ralr_knn)
print()
acc_s_knn=accuracy_score(Y_test,Y_pred)
print("Accuracy score by KNN method:",acc_s_knn)

Confusion matrix by KNN  method:
 [[83  9  0  0]
 [ 7 69 21  0]
 [ 0 22 77 10]
 [ 0  0  5 97]]

Classfication rep by KNN method:
               precision    recall  f1-score   support

           0       0.92      0.90      0.91        92
           1       0.69      0.71      0.70        97
           2       0.75      0.71      0.73       109
           3       0.91      0.95      0.93       102

    accuracy                           0.81       400
   macro avg       0.82      0.82      0.82       400
weighted avg       0.81      0.81      0.81       400


Accuracy score by KNN method: 0.815


In [13]:
#predicting using RandomForestRegresor

from sklearn.ensemble import RandomForestClassifier

model_RandomForest= RandomForestClassifier(n_estimators=50,random_state=10,
                                         bootstrap=True)
model_RandomForest.fit(X_train,Y_train)
Y_pred=model_RandomForest.predict(X_test)


In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr_knn=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by KNN  method:\n",cfmlr_knn)
print()
class_ralr_knn=classification_report(Y_test,Y_pred)
print("Classfication rep by KNN method:\n",class_ralr_knn)
print()
acc_s_knn=accuracy_score(Y_test,Y_pred)
print("Accuracy score by KNN method:",acc_s_knn)

Confusion matrix by KNN  method:
 [[86  6  0  0]
 [ 8 83  6  0]
 [ 0 17 87  5]
 [ 0  0  9 93]]

Classfication rep by KNN method:
               precision    recall  f1-score   support

           0       0.91      0.93      0.92        92
           1       0.78      0.86      0.82        97
           2       0.85      0.80      0.82       109
           3       0.95      0.91      0.93       102

    accuracy                           0.87       400
   macro avg       0.87      0.88      0.87       400
weighted avg       0.87      0.87      0.87       400


Accuracy score by KNN method: 0.8725


In [15]:
print((list(zip(mobile_df.columns[0:-1],
              model_RandomForest.feature_importances_))))

[('battery_power', 0.08005801831506018), ('clock_speed', 0.028135433312390976), ('fc', 0.02316367912340689), ('int_memory', 0.034594054506634844), ('m_dep', 0.024656280428355788), ('mobile_wt', 0.038158892525133756), ('n_cores', 0.023088030756526066), ('pc', 0.02806269955713679), ('px_height', 0.06473580831579014), ('px_width', 0.060069487325549266), ('ram', 0.510847746991545), ('sc_h', 0.025360267859301885), ('sc_w', 0.02935171192478371), ('talk_time', 0.02971788905838467)]


In [16]:
#Drop if very less Feature important
# new_df=mobile_df.drop(['blue','dual_sim','four_g','three_g','touch_screen','wifi'],axis=1)

# new_df.shape