In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
training_data = pd.read_excel(r'Titanic_Survival_Train (1).xls',index_col=0,header=0) 
testing_data = pd.read_excel(r'Titanic_Survival_Test.xls',index_col=0,header=0) 

In [3]:
training_data.head() 

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [4]:
testing_data.head()

Survived  Pclass  \
PassengerId                     
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   

                                                         Name     Sex   Age  \
PassengerId                                                                   
871                                         Balkic, Mr. Cerin    male  26.0   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0   
873                                  Carlsson, Mr. Frans Olof    male  33.0   
874                               Vander Cruyssen, Mr. Victor    male  47.0   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0   

             SibSp  Parch     Ticket     Fare        Cabin Embarked  
PassengerId                                                          
871              0      0     349248   7.8958          NaN        S  
872              1      1      11751  52.5542          D35        S  
873              0      0        695   5.0000  B51 B53 B55        S  
874              0      0     345765   9.0000          NaN        S  
875              1      0  P/PP 3381  24.0000          NaN        C

In [5]:
#feature selection 
training_data =training_data[['Name','Pclass','Sex','Age','Survived']]
testing_data =testing_data[['Name','Pclass','Sex','Age','Survived']]
print(training_data.shape)
print(testing_data.shape)

(891, 5)
(21, 5)


In [6]:
training_data.describe(include='all')

Name      Pclass   Sex         Age    Survived
count                       891  891.000000   891  714.000000  891.000000
unique                      891         NaN     2         NaN         NaN
top     Braund, Mr. Owen Harris         NaN  male         NaN         NaN
freq                          1         NaN   577         NaN         NaN
mean                        NaN    2.308642   NaN   29.699118    0.383838
std                         NaN    0.836071   NaN   14.526497    0.486592
min                         NaN    1.000000   NaN    0.420000    0.000000
25%                         NaN    2.000000   NaN   20.125000    0.000000
50%                         NaN    3.000000   NaN   28.000000    0.000000
75%                         NaN    3.000000   NaN   38.000000    1.000000
max                         NaN    3.000000   NaN   80.000000    1.000000

In [7]:
testing_data.describe(include='all')

Name     Pclass   Sex        Age   Survived
count                  21  21.000000    21  19.000000  21.000000
unique                 21        NaN     2        NaN        NaN
top     Balkic, Mr. Cerin        NaN  male        NaN        NaN
freq                    1        NaN    12        NaN        NaN
mean                  NaN   2.333333   NaN  29.842105   0.333333
std                   NaN   0.856349   NaN  10.766528   0.483046
min                   NaN   1.000000   NaN  15.000000   0.000000
25%                   NaN   2.000000   NaN  23.500000   0.000000
50%                   NaN   3.000000   NaN  27.000000   0.000000
75%                   NaN   3.000000   NaN  33.000000   1.000000
max                   NaN   3.000000   NaN  56.000000   1.000000

In [8]:
#finding the missing values
print(training_data.isnull().sum())
print()
print(testing_data.isnull().sum())

Name          0
Pclass        0
Sex           0
Age         177
Survived      0
dtype: int64

Name        0
Pclass      0
Sex         0
Age         2
Survived    0
dtype: int64


In [9]:
training_data.Age.mean()

29.69911764705882

In [10]:
#inputing numerical missing data into mean value

training_data['Age'].fillna(int(training_data['Age'].mean()),inplace=True)
print(training_data.isnull().sum())

print()
testing_data['Age'].fillna(int(testing_data['Age'].mean()),inplace=True)
print(testing_data.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


In [11]:
training_data['Sex'].replace({'female':0,'male':1},inplace=True)
testing_data['Sex'].replace({'female':0,'male':1},inplace=True)

In [12]:
print(training_data.head())

print(testing_data.head())

                                                          Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   

              Age  Survived  
PassengerId                  
1            22.0         0  
2            38.0         1  
3            26.0         1  
4            35.0         1  
5            35.0         0  
                                                         Name  Pclass  Sex  \
PassengerId                                                                  
871                                         Balkic, Mr. Cerin       3    1   
87

In [13]:
training_data.info

<bound method DataFrame.info of                                                           Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   
...                                                        ...     ...  ...   
887                                      Montvila, Rev. Juozas       2    1   
888                               Graham, Miss. Margaret Edith       1    0   
889                   Johnston, Miss. Catherine Helen "Carrie"       3    0   
890                                      Behr, Mr. Karl Howell       1    1   
891                 

In [14]:
X_train=training_data.values[0:870,1:-1]
Y_train=training_data.values[0:870,-1]
Y_train=Y_train.astype(int)

X_test=testing_data.values[:,1:-1]
Y_test=testing_data.values[:,-1]
Y_test=Y_test.astype(int)

In [15]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(870, 3)
(870,)
(21, 3)
(21,)


In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)
#scaler.fit_transform(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


In [17]:
X_train

array([[ 0.82810204,  0.73472649, -0.5784206 ],
       [-1.56541549, -1.3610507 ,  0.64650051],
       [ 0.82810204, -1.3610507 , -0.27219032],
       ...,
       [-1.56541549,  0.73472649,  0.11059753],
       [ 0.82810204,  0.73472649, -0.04251761],
       [ 0.82810204,  0.73472649, -1.95645684]])

In [18]:
Y_test

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [19]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='euclidean')
#euclidean, manhattan, minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 0), (0, 0)]


In [20]:
np.sqrt(len(X_train))

29.49576240750525

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix:")
print(cfm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication report:")
print(class_r)
acc=accuracy_score(Y_test,Y_pred)
print("Accuracy score:",acc)

Confusion matrix:
[[13  1]
 [ 2  5]]
Classfication report:
              precision    recall  f1-score   support

           0       0.87      0.93      0.90        14
           1       0.83      0.71      0.77         7

    accuracy                           0.86        21
   macro avg       0.85      0.82      0.83        21
weighted avg       0.86      0.86      0.85        21

Accuracy score: 0.8571428571428571


In [22]:
row={'Pclass':1,'Sex':1,'Age':24}
#convert it into a dataframe
Titanic_Survive_Test_df=pd.DataFrame(data=row,index=[0])
Titanic_Survive_Test_df

Pclass  Sex  Age
0       1    1   24

In [23]:
Titanic_Survive_Test_df=scaler.transform(Titanic_Survive_Test_df)
Titanic_Survive_Test_df

C:\Users\Shreyas\Anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


array([[-1.56541549,  0.73472649, -0.42530546]])

In [24]:
Y_pred_temp=model_KNN.predict(Titanic_Survive_Test_df)
Y_pred_temp

array([0])

In [25]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    model_KNN = KNeighborsClassifier(n_neighbors=K,metric="euclidean")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is  0.7619047619047619 for K-Value: 1
Accuracy is  0.8095238095238095 for K-Value: 2
Accuracy is  0.8095238095238095 for K-Value: 3
Accuracy is  0.8571428571428571 for K-Value: 4
Accuracy is  0.8571428571428571 for K-Value: 5
Accuracy is  0.8095238095238095 for K-Value: 6
Accuracy is  0.8095238095238095 for K-Value: 7
Accuracy is  0.8571428571428571 for K-Value: 8
Accuracy is  0.8095238095238095 for K-Value: 9
Accuracy is  0.9047619047619048 for K-Value: 10
Accuracy is  0.8571428571428571 for K-Value: 11
Accuracy is  0.9047619047619048 for K-Value: 12
Accuracy is  0.9047619047619048 for K-Value: 13
Accuracy is  0.8571428571428571 for K-Value: 14
Accuracy is  0.9047619047619048 for K-Value: 15
Accuracy is  0.8571428571428571 for K-Value: 16
Accuracy is  0.8571428571428571 for K-Value: 17
Accuracy is  0.8095238095238095 for K-Value: 18
Accuracy is  0.8571428571428571 for K-Value: 19
Accuracy is  0.8095238095238095 for K-Value: 20
Accuracy is  0.8095238095238095 for K-Value: 21
A

In [26]:
my_dict

{1: 0.7619047619047619,
 2: 0.8095238095238095,
 3: 0.8095238095238095,
 4: 0.8571428571428571,
 5: 0.8571428571428571,
 6: 0.8095238095238095,
 7: 0.8095238095238095,
 8: 0.8571428571428571,
 9: 0.8095238095238095,
 10: 0.9047619047619048,
 11: 0.8571428571428571,
 12: 0.9047619047619048,
 13: 0.9047619047619048,
 14: 0.8571428571428571,
 15: 0.9047619047619048,
 16: 0.8571428571428571,
 17: 0.8571428571428571,
 18: 0.8095238095238095,
 19: 0.8571428571428571,
 20: 0.8095238095238095,
 21: 0.8095238095238095,
 22: 0.8571428571428571,
 23: 0.8095238095238095,
 24: 0.8095238095238095,
 25: 0.8095238095238095,
 26: 0.8571428571428571,
 27: 0.8571428571428571,
 28: 0.8571428571428571,
 29: 0.8571428571428571,
 30: 0.8571428571428571}

In [27]:
for K in my_dict:
    if my_dict[K]==max(my_dict.values()):
        print(K,":",my_dict[K])

10 : 0.9047619047619048
12 : 0.9047619047619048
13 : 0.9047619047619048
15 : 0.9047619047619048


In [28]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='euclidean')
#euclidean, manhattan, minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 0), (0, 0)]


In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix:")
print(cfm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication report:")
print(class_r)
acc=accuracy_score(Y_test,Y_pred)
print("Accuracy score:",acc)

Confusion matrix:
[[13  1]
 [ 2  5]]
Classfication report:
              precision    recall  f1-score   support

           0       0.87      0.93      0.90        14
           1       0.83      0.71      0.77         7

    accuracy                           0.86        21
   macro avg       0.85      0.82      0.83        21
weighted avg       0.86      0.86      0.85        21

Accuracy score: 0.8571428571428571


In [30]:
from sklearn.linear_model import LogisticRegression
#create a model 
classifier=LogisticRegression()
#fitting training data to the model 
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix:")
print(cfm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication report:")
print(class_r)
acc=accuracy_score(Y_test,Y_pred)
print("Accuracy score:",acc)

Confusion matrix:
[[12  2]
 [ 0  7]]
Classfication report:
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

Accuracy score: 0.9047619047619048


In [32]:
testing_data['Y_pred']=Y_pred
testing_data

Name  Pclass  Sex  \
PassengerId                                                                  
871                                         Balkic, Mr. Cerin       3    1   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)       1    0   
873                                  Carlsson, Mr. Frans Olof       1    1   
874                               Vander Cruyssen, Mr. Victor       3    1   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)       2    0   
876                          Najib, Miss. Adele Kiamie "Jane"       3    0   
877                             Gustafsson, Mr. Alfred Ossian       3    1   
878                                      Petroff, Mr. Nedelio       3    1   
879                                        Laleff, Mr. Kristo       3    1   
880             Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)       1    0   
881              Shelley, Mrs. William (Imanita Parrish Hall)       2    0   
882                                        Markun, Mr. Johann       3    1   
883                              Dahlberg, Miss. Gerda Ulrika       3    0   
884                             Banfield, Mr. Frederick James       2    1   
885                                    Sutehall, Mr. Henry Jr       3    1   
886                      Rice, Mrs. William (Margaret Norton)       3    0   
887                                     Montvila, Rev. Juozas       2    1   
888                              Graham, Miss. Margaret Edith       1    0   
889                  Johnston, Miss. Catherine Helen "Carrie"       3    0   
890                                     Behr, Mr. Karl Howell       1    1   
891                                       Dooley, Mr. Patrick       3    1   

              Age  Survived  Y_pred  
PassengerId                          
871          26.0         0       0  
872          47.0         1       1  
873          33.0         0       0  
874          47.0         0       0  
875          28.0         1       1  
876          15.0         1       1  
877          20.0         0       0  
878          19.0         0       0  
879          29.0         0       0  
880          56.0         1       1  
881          25.0         1       1  
882          33.0         0       0  
883          22.0         0       1  
884          28.0         0       0  
885          25.0         0       0  
886          39.0         0       0  
887          27.0         0       0  
888          19.0         1       1  
889          29.0         0       1  
890          26.0         1       1  
891          32.0         0       0

# Regression with KNN

In [33]:
data=pd.read_csv(r'Advertising.csv',index_col=0,header=0)
data.head(10)

FileNotFoundError: [Errno 2] No such file or directory: 'Advertising.csv'

In [ ]:
data.isnull().sum()

In [ ]:
X = data[['TV', 'radio', 'newspaper']]
Y = data['sales']

In [ ]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=10)


In [ ]:
X_train.shape

In [ ]:
Y_train.shape

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)
#scaler.fit_transform(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
int(np.sqrt(len(X_train)))

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
model_KNN=KNeighborsRegressor(n_neighbors=12,metric='euclidean')

model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))


In [ ]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np
 
r2=r2_score(Y_test,Y_pred)
print("R-squared:",r2)
 
rmse=np.sqrt(mean_squared_error(Y_test,Y_pred))
print("RMSE:",rmse)
 
adjusted_r_squared = 1 - (1-r2)*(len(Y)-1)/(len(Y)-X.shape[1]-1)
print("Adj R-square:",adjusted_r_squared)

In [ ]:
from sklearn.metrics import r2_score

for K in range(1,16):
    model_KNN = KNeighborsRegressor(n_neighbors=K,metric='euclidean')
    model_KNN.fit(X_train,Y_train)
    Y_pred= model_KNN.predict(X_test)
    print('R-square is',r2_score(Y_test,Y_pred),'for K-Value:',K)