In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import SGDClassifier
import warnings
warnings.filterwarnings("ignore")

In [2]:
cars_train=pd.read_csv(r'cars_train.csv',header=None)
cars_test=pd.read_csv(r'cars_test.csv',header=None)

In [3]:
cars_train.head()

0      1      2     3      4    5      6
0  vhigh   high      3  more  small  low  unacc
1    low  vhigh      3     4  small  med  unacc
2    low   high  5more  more    big  low  unacc
3   high    med      4     2  small  med  unacc
4    low    low      3  more    big  med   good

In [4]:
cars_test.head()

0      1      2     3      4     5      6
0    med  vhigh  5more     4  small   low  unacc
1  vhigh   high      2     2    big   med  unacc
2    low   high      2  more  small   low  unacc
3  vhigh  vhigh      3     2    big  high  unacc
4    low    med      4     4    med   med   good

In [5]:
cars_train.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [6]:
cars_train

buying  maint  doors persons lug_boot safety classes
0     vhigh   high      3    more    small    low   unacc
1       low  vhigh      3       4    small    med   unacc
2       low   high  5more    more      big    low   unacc
3      high    med      4       2    small    med   unacc
4       low    low      3    more      big    med    good
...     ...    ...    ...     ...      ...    ...     ...
1377    low  vhigh  5more       4      big    med     acc
1378    low  vhigh      3    more      med    low   unacc
1379   high  vhigh  5more       4      med   high   unacc
1380    med    med      4       4      big    low   unacc
1381    med    low  5more    more    small   high    good

[1382 rows x 7 columns]

In [7]:
#Checking for missing values
cars_train.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [8]:
cars_test.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [9]:
cars_test.drop('classes',axis=1,inplace=True)
#remoe the Y variable bcuase we need to predict it

In [10]:
cars_test.head()

buying  maint  doors persons lug_boot safety
0    med  vhigh  5more       4    small    low
1  vhigh   high      2       2      big    med
2    low   high      2    more    small    low
3  vhigh  vhigh      3       2      big   high
4    low    med      4       4      med    med

In [59]:
cars_train.persons.value_counts()

2    466
1    462
0    454
Name: persons, dtype: int64

In [61]:
cars_train.safety.value_counts()

0    463
2    461
1    458
Name: safety, dtype: int64

In [11]:
colname=cars_train.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for x in colname:
    cars_train[x]=le.fit_transform(cars_train[x])

In [13]:
cars_train.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      0      1        2         2       1        2
1       1      3      1        1         2       2        2
2       1      0      3        2         0       1        2
3       0      2      2        0         2       2        2
4       1      1      1        2         0       2        1

In [14]:
colname1=cars_test.columns
colname1

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for x in colname1:
    cars_test[x]=le.fit_transform(cars_test[x])

In [16]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [17]:
X = cars_train.values[:,0:-1]
Y = cars_train.values[:,-1]
Y = Y.astype(int)

In [18]:
X.shape

(1382, 6)

In [19]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(X)
X= scaler.transform(X)


In [20]:
X

array([[ 1.33507272, -1.3488262 , -0.45682233,  1.21505861,  1.22565305,
         0.00176987],
       [-0.44760409,  1.32688358, -0.45682233, -0.01064285,  1.22565305,
         1.22474807],
       [-0.44760409, -1.3488262 ,  1.33418038,  1.21505861, -1.21505663,
         0.00176987],
       ...,
       [-1.33894249,  1.32688358,  1.33418038, -0.01064285,  0.00529821,
        -1.22120833],
       [ 0.44373431,  0.43498032,  0.43867903, -0.01064285, -1.21505663,
         0.00176987],
       [ 0.44373431, -0.45692294,  1.33418038,  1.21505861,  1.22565305,
        -1.22120833]])

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test= train_test_split(X, Y, test_size=0.2, random_state=10)

In [62]:
X_train.shape

(1105, 6)

## Running Decision Tree Model 

In [22]:
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree= DecisionTreeClassifier(criterion='gini',
                                           random_state=10,
                                           splitter="best" )

model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

# Hyper parameters can be tuned with the help of grid search Validation

# If the score function and the accuracy shows a major difference
#If the plotted tree has a lot of leaf loads consisting of one or two observations

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Log Reg:")
print(cfmlr)
class_rlr=classification_report(Y_test,Y_pred)
print("Classfication rep by Log reg:")
print(class_rlr)
acc_slr=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Log reg:",acc_slr)

Confusion matrix by Log Reg:
[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classfication rep by Log reg:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277

Accuracy score by Log reg: 0.9783393501805054


In [24]:
model_DecisionTree.score(X_train,Y_train)
#If there is high difference between Accuracy and score then the model is overfitted
#Here the accuracy is 0.9783 and score is 1.0 thus the difference is low, the model is not overfitted

1.0

In [25]:
print((list(zip(cars_train.columns[0:-1],
              model_DecisionTree.feature_importances_))))

[('buying', 0.21976792783843332), ('maint', 0.18220929667385857), ('doors', 0.062005934167191426), ('persons', 0.19425872158174767), ('lug_boot', 0.09772725134941933), ('safety', 0.24403086838934968)]


In [26]:
sample=pd.DataFrame()

sample["Column"]=cars_train.columns[0:-1]
sample["Imp value"]=model_DecisionTree.feature_importances_

sample.sort_values("Imp value",ascending=False)
#Checking importance of each variable in the dataset for building the model 

Column  Imp value
5    safety   0.244031
0    buying   0.219768
3   persons   0.194259
1     maint   0.182209
4  lug_boot   0.097727
2     doors   0.062006

In [27]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DecisionTree, feature_names=cars_train.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

In [28]:
model_DecisionTree

DecisionTreeClassifier(random_state=10)

In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
 
# first, initialize the classificators
tree= DecisionTreeClassifier(random_state=10) # using the random state for reproducibility
knn= KNeighborsClassifier(n_neighbors=5,metric='euclidean')
svm= SVC(kernel="rbf", gamma=0.1, C=90,random_state=10)
logreg=LogisticRegression(multi_class="multinomial",random_state=10)

In [30]:
# now, create a list with the objects 
models= [tree, knn, svm, logreg]

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
 
for model in models:
    
    model.fit(X_train, Y_train) # fit the model
    Y_pred= model.predict(X_test) # then predict on the test set
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred)
    
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
The accuracy of the  DecisionTreeClassifier  model is  97.83393501805054
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277



[[ 65   1   5   0]
 [  8   4   0   0]
 [  1   0 184   0]
 [  2   0   1   6]]
The accuracy of the  KNeighborsClassifier  model is  93.50180505415162
Classification report:
               precision    recall  f1-score   support

           0       0.86      0.92      0.88        71
           1       0.80      0.33      0.47        12
           2       0.97      0.99      0.98       185


In [32]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [33]:
test = cars_test.values
test = scaler.transform(test)
print(test)

[[ 0.44373431  1.32688358  1.33418038 -0.01064285  1.22565305  0.00176987]
 [ 1.33507272 -1.3488262  -1.35232368 -1.23634431 -1.21505663  1.22474807]
 [-0.44760409 -1.3488262  -1.35232368  1.21505861  1.22565305  0.00176987]
 ...
 [ 0.44373431 -0.45692294 -0.45682233 -1.23634431  1.22565305 -1.22120833]
 [ 1.33507272  0.43498032 -1.35232368  1.21505861  1.22565305  0.00176987]
 [ 1.33507272 -1.3488262  -0.45682233 -0.01064285  1.22565305  1.22474807]]


In [34]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree = DecisionTreeClassifier(criterion='gini',random_state=10,splitter='best')    #best is used to get the homogeneous data and random will split the data randomly(length of tree could increase)

#fitting the model and predicting the values
model_DecisionTree.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=10)

In [35]:
test_pred = model_DecisionTree.predict(test)
test_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2,
       0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 3, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 2, 0, 3, 3, 0, 2,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [36]:
cars_test = pd.read_csv(r"cars_test.csv",header=None)
cars_test.columns=['buying','maint','doors','persons',
                   'lug_boot','safety','classes']
cars_test["Pred"]=test_pred
cars_test["Pred"]=cars_test["Pred"].replace({0:"acc",1:"good",2:"unacc",
                                         3:"vgood"})
cars_test.head()

buying  maint  doors persons lug_boot safety classes   Pred
0    med  vhigh  5more       4    small    low   unacc  unacc
1  vhigh   high      2       2      big    med   unacc  unacc
2    low   high      2    more    small    low   unacc  unacc
3  vhigh  vhigh      3       2      big   high   unacc  unacc
4    low    med      4       4      med    med    good   good

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm = confusion_matrix(cars_test.classes, cars_test.Pred)
print("cfm :",cfm)
print()
print("Classification report :")
print(classification_report(cars_test.classes, cars_test.Pred))

acc = accuracy_score(cars_test.classes, cars_test.Pred)
print("Accuracy of the model :",acc)

cfm : [[ 60   1   3   0]
 [  3  10   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]

Classification report :
              precision    recall  f1-score   support

         acc       0.95      0.94      0.94        64
        good       0.91      0.77      0.83        13
       unacc       0.99      1.00      0.99       251
       vgood       1.00      1.00      1.00        18

    accuracy                           0.98       346
   macro avg       0.96      0.93      0.94       346
weighted avg       0.98      0.98      0.98       346

Accuracy of the model : 0.9797687861271677


In [38]:
cars_test.to_excel("Decision_Tree Test outplut.xlsx",header=True)

## Predicting the random_forest_classifier 

In [39]:
#predicting the random_forest_classifier 
from sklearn.ensemble import RandomForestClassifier

model_RandomForest = RandomForestClassifier (n_estimators=100,
                                            random_state=10, bootstrap=True,
                                            n_jobs=-1)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Log Reg:")
print(cfmlr)
class_rlr=classification_report(Y_test,Y_pred)
print("Classfication rep by Log reg:")
print(class_rlr)
acc_slr=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Log reg:",acc_slr)

Confusion matrix by Log Reg:
[[ 65   1   5   0]
 [  4   8   0   0]
 [  1   0 184   0]
 [  0   0   0   9]]
Classfication rep by Log reg:
              precision    recall  f1-score   support

           0       0.93      0.92      0.92        71
           1       0.89      0.67      0.76        12
           2       0.97      0.99      0.98       185
           3       1.00      1.00      1.00         9

    accuracy                           0.96       277
   macro avg       0.95      0.89      0.92       277
weighted avg       0.96      0.96      0.96       277

Accuracy score by Log reg: 0.9602888086642599


In [41]:
#predicting the random_forest_classifier 
from sklearn.ensemble import RandomForestClassifier

model_RandomForest = RandomForestClassifier (n_estimators=100,
                                            random_state=10, bootstrap=True,
                                            n_jobs=-1)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [42]:
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT=ExtraTreesClassifier( random_state=10, bootstrap=True)
 
parameter_space = {
    'n_estimators':[100,200,300,400,500],
    'max_depth':[10,15, 8, 12]
    }
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(model_EXT, parameter_space, n_jobs=-1, cv=5)

In [43]:
clf.fit(X_train,Y_train)

GridSearchCV(cv=5,
             estimator=ExtraTreesClassifier(bootstrap=True, random_state=10),
             n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'n_estimators': [100, 200, 300, 400, 500]})

In [44]:
print('Best Parameter::>',clf.best_params_)

Best Parameter::> {'max_depth': 12, 'n_estimators': 100}


In [45]:
model_EXT.fit(X_train,Y_train)
Y_pred=model_EXT.predict(X_test)

In [46]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Log Reg:")
print(cfmlr)
class_rlr=classification_report(Y_test,Y_pred)
print("Classfication rep by Log reg:")
print(class_rlr)
acc_slr=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Log reg:",acc_slr)

Confusion matrix by Log Reg:
[[ 64   0   7   0]
 [  8   4   0   0]
 [  2   0 183   0]
 [  2   0   0   7]]
Classfication rep by Log reg:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87        71
           1       1.00      0.33      0.50        12
           2       0.96      0.99      0.98       185
           3       1.00      0.78      0.88         9

    accuracy                           0.93       277
   macro avg       0.95      0.75      0.81       277
weighted avg       0.93      0.93      0.93       277

Accuracy score by Log reg: 0.9314079422382672


In [47]:
#predicting using the Adaboost_Classifier
from sklearn.ensemble import AdaBoostClassifier
 
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),
                                 n_estimators=100,random_state=10)
#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)

In [48]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Log Reg:")
print(cfmlr)
class_rlr=classification_report(Y_test,Y_pred)
print("Classfication rep by Log reg:")
print(class_rlr)
acc_slr=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Log reg:",acc_slr)

Confusion matrix by Log Reg:
[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classfication rep by Log reg:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277

Accuracy score by Log reg: 0.9783393501805054


In [49]:
#predicting using the Gradient_Boosting_Classifier
from sklearn.ensemble import GradientBoostingClassifier
 
model_GradientBoosting=GradientBoostingClassifier(n_estimators=300,random_state=10)
#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,Y_train)
Y_pred=model_GradientBoosting.predict(X_test)

In [50]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Log Reg:")
print(cfmlr)
class_rlr=classification_report(Y_test,Y_pred)
print("Classfication rep by Log reg:")
print(class_rlr)
acc_slr=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Log reg:",acc_slr)

Confusion matrix by Log Reg:
[[ 71   0   0   0]
 [  1  11   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classfication rep by Log reg:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        71
           1       1.00      0.92      0.96        12
           2       1.00      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           1.00       277
   macro avg       1.00      0.98      0.99       277
weighted avg       1.00      1.00      1.00       277

Accuracy score by Log reg: 0.9963898916967509


In [51]:
!pip install XGBoost

In [52]:
## Running XGBoost
from xgboost import XGBClassifier

model_GradientBoosting = XGBClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values 
model_GradientBoosting.fit(X_train,Y_train)

Y_pred= model_GradientBoosting.predict(X_test)

In [53]:
!pip install xgboost

In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Log Reg:")
print(cfmlr)
class_rlr=classification_report(Y_test,Y_pred)
print("Classfication rep by Log reg:")
print(class_rlr)
acc_slr=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Log reg:",acc_slr)

Confusion matrix by Log Reg:
[[ 69   1   1   0]
 [  3   9   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classfication rep by Log reg:
              precision    recall  f1-score   support

           0       0.96      0.97      0.97        71
           1       0.90      0.75      0.82        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.93      0.95       277
weighted avg       0.98      0.98      0.98       277

Accuracy score by Log reg: 0.9819494584837545


## Ensemble Model

In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
 
# create the sub models
estimators = []
#model1 = LogisticRegression()
#estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
estimators.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
estimators.append(('knn', model4))
 
 
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [56]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Log Reg:")
print(cfmlr)
class_rlr=classification_report(Y_test,Y_pred)
print("Classfication rep by Log reg:")
print(class_rlr)
acc_slr=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Log reg:",acc_slr)

Confusion matrix by Log Reg:
[[ 69   0   2   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classfication rep by Log reg:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       1.00      0.67      0.80        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.98      0.91      0.94       277
weighted avg       0.98      0.98      0.98       277

Accuracy score by Log reg: 0.9783393501805054


In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier
 
# create the sub models
level0 = []
model1 = LogisticRegression()
level0.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
level0.append(('cart', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
level0.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
level0.append(('knn', model4))
 
level1=LogisticRegression()
 
# create the ensemble model
ensemble = StackingClassifier(estimators=level0, final_estimator=level1,
                              cv=5,passthrough=False)   
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)
#passthrough - It will only learn on the combination of the predictions,if true will learn on the whole model
#Bcuase we building Linear Regression model too passthrough true not required

In [58]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmlr=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Log Reg:")
print(cfmlr)
class_rlr=classification_report(Y_test,Y_pred)
print("Classfication rep by Log reg:")
print(class_rlr)
acc_slr=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Log reg:",acc_slr)

Confusion matrix by Log Reg:
[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classfication rep by Log reg:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        71
           1       1.00      0.83      0.91        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.99       277
   macro avg       0.99      0.95      0.97       277
weighted avg       0.99      0.99      0.99       277

Accuracy score by Log reg: 0.9855595667870036
